background {
    monitor =
    path = /usr/share/hypr/wall2.png
    blur_passes = 3
    blur_size = 4 
}

label {
    monitor =
    text = $TIME
    font_size = 84
    font_family = Sans
    position = 0, 80
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 250, 40
    position = 0, -80
    halign = center
    valign = center
    outline_thickness = 1
}